// tt_um_saltworks_ndf — the NDF top module.
//
// HAND RTL BY RULING (D2(b) exemption list: pin wrapper + sequencer + fabric).
// The four MAC cells and the three SER organs instantiated below are KERNEL
// EMISSIONS (emitSeqShell / emitSeqMux) and carry their own counted criteria.
// Generated by docs/hdl-tools/gen_ndf_wrapper.py - edit the generator, not this.
//
// SCOPE (silicon's clause, adopted verbatim): a layout of this composition
// measures area / timing / DRC / LVS / antenna. It is NOT a functional demo
// and NOT a tile-fit signoff. Functional correctness is fence-held.
//
// POWER-GATING LAW: no `initial`. Every register reloads at its own strobe;
// the counters realign at sof or rst_n.

`default_nettype none

module tt_um_saltworks_ndf (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
  // ---- D6 pin map (frozen) ----
  wire       sof         = uio_in[6];
  wire       edge_in_dat = uio_in[2];
  wire       edge_in_vld = uio_in[3];
  wire [1:0] phase_o;
  wire       edge_out_dat, edge_out_vld, valid;
  assign uio_oe  = 8'b1011_0011;
  assign uio_out = {valid, 1'b0, edge_out_vld, edge_out_dat,
                    1'b0, 1'b0, phase_o[1], phase_o[0]};

  // ---- the core, as-is (R4: demonstrates on its own bus) ----
  slicea16bma core (
    .clk(clk), .rst_n(rst_n),
    .instr_byte(ui_in), .addr_byte(uo_out), .phase_o(phase_o)
  );

  // ---- the fabric. Port indices FROZEN (D6): 0-3 cells, 4 edge-in,
  //      5 edge-out, 6 CPU-stub, 7 spare ----
  wire [7:0] fab_in, fab_out;
  wire [3:0] cnt_o;
  banyan_fabric #(.PAYLOAD(8)) fab (
    .clk(clk), .rst_n(rst_n), .sof(sof),
    .din(fab_in), .dout(fab_out), .cnt_o(cnt_o), .valid(valid)
  );
  assign fab_in[4] = edge_in_dat;
  assign fab_in[5] = 1'b0;   // edge-out is a DESTINATION: nothing sends into it
  assign fab_in[6] = 1'b0;
  assign fab_in[7] = 1'b0;
  assign edge_out_dat = fab_out[5];
  assign edge_out_vld = valid;

  // ---- the 2-2-1 sequencer (hand RTL, D2(b)): 22 frames x 14 cycles ----
  reg [3:0] cyc;
  reg [4:0] frm;
  wire frame_end = (cyc == 4'd13);
  always @(posedge clk) begin
    if (!rst_n || sof) begin cyc <= 4'd0; frm <= 5'd0; end
    else begin
      cyc <= frame_end ? 4'd0 : cyc + 4'd1;
      if (frame_end && frm != 5'd22) frm <= frm + 5'd1;
    end
  end
  wire payload  = (cyc >= 4'd6);
  wire sign_cyc = (cyc == 4'd13);

  wire ld_f0 = (frm==5'd0)||(frm==5'd3)||(frm==5'd8);
  wire ld_f1 = (frm==5'd1)||(frm==5'd4)||(frm==5'd9);
  wire ld_f2 = (frm==5'd2)||(frm==5'd5)||(frm==5'd14);
  wire st_f0 = (frm==5'd6)||(frm==5'd11);
  wire st_f1 = (frm==5'd7)||(frm==5'd12);
  wire st_f2 = (frm==5'd13)||(frm==5'd17);

  // 24 sign-extension cycles after each 8-bit payload (LOAD_W = 32 canonical)
  reg [4:0] ext0, ext1, ext2;
  always @(posedge clk) begin
    if (!rst_n || sof) begin ext0<=5'd0; ext1<=5'd0; ext2<=5'd0; end
    else begin
      if (ld_f0 && frame_end) ext0 <= 5'd24; else if (ext0!=0) ext0 <= ext0-5'd1;
      if (ld_f1 && frame_end) ext1 <= 5'd24; else if (ext1!=0) ext1 <= ext1-5'd1;
      if (ld_f2 && frame_end) ext2 <= 5'd24; else if (ext2!=0) ext2 <= ext2-5'd1;
    end
  end

  // sign-hold: the sender sends 8 bits ONCE (D4h); replay the MSB through
  // the extension window. One flop per cell.
  reg sh0, sh1, sh2;
  always @(posedge clk) begin
    if (ld_f0 && sign_cyc) sh0 <= fab_out[0];
    if (ld_f1 && sign_cyc) sh1 <= fab_out[1];
    if (ld_f2 && sign_cyc) sh2 <= fab_out[2];
  end

  wire bias0 = (frm==5'd2) && (cyc==4'd11);
  wire bias1 = (frm==5'd3) && (cyc==4'd11);
  wire bias2 = (frm==5'd4) && (cyc==4'd11);

  wire x0 = bias0 ? 1'b1 : (ld_f0 && payload) ? fab_out[0]
          : (ext0!=0) ? sh0 : (st_f0 && payload) ? fab_out[0] : 1'b0;
  wire x1 = bias1 ? 1'b1 : (ld_f1 && payload) ? fab_out[1]
          : (ext1!=0) ? sh1 : (st_f1 && payload) ? fab_out[1] : 1'b0;
  wire x2 = bias2 ? 1'b1 : (ld_f2 && payload) ? fab_out[2]
          : (ext2!=0) ? sh2 : (st_f2 && payload) ? fab_out[2] : 1'b0;
  wire load0 = (ld_f0 && payload) || (ext0!=0);
  wire load1 = (ld_f1 && payload) || (ext1!=0);
  wire load2 = (ld_f2 && payload) || (ext2!=0);
  wire sgn0  = st_f0 && sign_cyc;
  wire sgn1  = st_f1 && sign_cyc;
  wire sgn2  = st_f2 && sign_cyc;

  // R6 shell strobes. en_wsh spans load/extension/stream/bias; en_acc only
  // stream+bias (the acc HOLDS during load, or the live AND row dribbles
  // andWord(w_bit, residue) into it).
  wire en_w0 = load0 || (st_f0 && payload) || bias0;
  wire en_w1 = load1 || (st_f1 && payload) || bias1;
  wire en_w2 = load2 || (st_f2 && payload) || bias2;
  wire en_a0 = (st_f0 && payload) || bias0;
  wire en_a1 = (st_f1 && payload) || bias1;
  wire en_a2 = (st_f2 && payload) || bias2;
  wire clr   = (frm==5'd0) && (cyc==4'd0);

  // ACTIVATE strobes: the SER parallel-load. c0@F12, c1@F13, c2@F18.
  // SER parallel-load: latch the SETTLED accumulator at frame end, one frame
  // before its emit window. (Draft v2's ser_ld1 carried an open ADOPTION CALL
  // between F13 and F16; F16 is taken - it latches immediately before the F17
  // emit window, and the acc holds either way because en_acc is low there.)
  wire act0 = (frm==5'd12) && frame_end;
  wire act1 = (frm==5'd16) && frame_end;
  wire act2 = (frm==5'd17) && frame_end;

  wire [31:0] acc0, acc1, acc2, acc3;
  wire ser0_out, ser1_out, ser2_out;

  // ---- the cells: KERNEL-EMITTED (emitSeqShell, L2) ----
  mac_cell_signed_shell cell0 (
    .clk(clk),
    .clr(clr),
    .en_wsh(en_w0),
    .en_acc(en_a0),
    .i0(x0),
    .i1(load0),
    .i2(sgn0),
    .o0(acc0[0]),
    .o1(acc0[1]),
    .o2(acc0[2]),
    .o3(acc0[3]),
    .o4(acc0[4]),
    .o5(acc0[5]),
    .o6(acc0[6]),
    .o7(acc0[7]),
    .o8(acc0[8]),
    .o9(acc0[9]),
    .o10(acc0[10]),
    .o11(acc0[11]),
    .o12(acc0[12]),
    .o13(acc0[13]),
    .o14(acc0[14]),
    .o15(acc0[15]),
    .o16(acc0[16]),
    .o17(acc0[17]),
    .o18(acc0[18]),
    .o19(acc0[19]),
    .o20(acc0[20]),
    .o21(acc0[21]),
    .o22(acc0[22]),
    .o23(acc0[23]),
    .o24(acc0[24]),
    .o25(acc0[25]),
    .o26(acc0[26]),
    .o27(acc0[27]),
    .o28(acc0[28]),
    .o29(acc0[29]),
    .o30(acc0[30]),
    .o31(acc0[31])
  );
  mac_cell_signed_shell cell1 (
    .clk(clk),
    .clr(clr),
    .en_wsh(en_w1),
    .en_acc(en_a1),
    .i0(x1),
    .i1(load1),
    .i2(sgn1),
    .o0(acc1[0]),
    .o1(acc1[1]),
    .o2(acc1[2]),
    .o3(acc1[3]),
    .o4(acc1[4]),
    .o5(acc1[5]),
    .o6(acc1[6]),
    .o7(acc1[7]),
    .o8(acc1[8]),
    .o9(acc1[9]),
    .o10(acc1[10]),
    .o11(acc1[11]),
    .o12(acc1[12]),
    .o13(acc1[13]),
    .o14(acc1[14]),
    .o15(acc1[15]),
    .o16(acc1[16]),
    .o17(acc1[17]),
    .o18(acc1[18]),
    .o19(acc1[19]),
    .o20(acc1[20]),
    .o21(acc1[21]),
    .o22(acc1[22]),
    .o23(acc1[23]),
    .o24(acc1[24]),
    .o25(acc1[25]),
    .o26(acc1[26]),
    .o27(acc1[27]),
    .o28(acc1[28]),
    .o29(acc1[29]),
    .o30(acc1[30]),
    .o31(acc1[31])
  );
  mac_cell_signed_shell cell2 (
    .clk(clk),
    .clr(clr),
    .en_wsh(en_w2),
    .en_acc(en_a2),
    .i0(x2),
    .i1(load2),
    .i2(sgn2),
    .o0(acc2[0]),
    .o1(acc2[1]),
    .o2(acc2[2]),
    .o3(acc2[3]),
    .o4(acc2[4]),
    .o5(acc2[5]),
    .o6(acc2[6]),
    .o7(acc2[7]),
    .o8(acc2[8]),
    .o9(acc2[9]),
    .o10(acc2[10]),
    .o11(acc2[11]),
    .o12(acc2[12]),
    .o13(acc2[13]),
    .o14(acc2[14]),
    .o15(acc2[15]),
    .o16(acc2[16]),
    .o17(acc2[17]),
    .o18(acc2[18]),
    .o19(acc2[19]),
    .o20(acc2[20]),
    .o21(acc2[21]),
    .o22(acc2[22]),
    .o23(acc2[23]),
    .o24(acc2[24]),
    .o25(acc2[25]),
    .o26(acc2[26]),
    .o27(acc2[27]),
    .o28(acc2[28]),
    .o29(acc2[29]),
    .o30(acc2[30]),
    .o31(acc2[31])
  );
  // cell 3: k=4 is forced by fabric ports; idle in the 2-2-1 demo —
  // clocked and cleared, never enabled. Real state, zero schedule.
  mac_cell_signed_shell cell3 (
    .clk(clk),
    .clr(clr),
    .en_wsh(1'b0),
    .en_acc(1'b0),
    .i0(1'b0),
    .i1(1'b0),
    .i2(1'b0),
    .o0(acc3[0]),
    .o1(acc3[1]),
    .o2(acc3[2]),
    .o3(acc3[3]),
    .o4(acc3[4]),
    .o5(acc3[5]),
    .o6(acc3[6]),
    .o7(acc3[7]),
    .o8(acc3[8]),
    .o9(acc3[9]),
    .o10(acc3[10]),
    .o11(acc3[11]),
    .o12(acc3[12]),
    .o13(acc3[13]),
    .o14(acc3[14]),
    .o15(acc3[15]),
    .o16(acc3[16]),
    .o17(acc3[17]),
    .o18(acc3[18]),
    .o19(acc3[19]),
    .o20(acc3[20]),
    .o21(acc3[21]),
    .o22(acc3[22]),
    .o23(acc3[23]),
    .o24(acc3[24]),
    .o25(acc3[25]),
    .o26(acc3[26]),
    .o27(acc3[27]),
    .o28(acc3[28]),
    .o29(acc3[29]),
    .o30(acc3[30]),
    .o31(acc3[31])
  );

  // ---- the SER/activation organs: KERNEL-EMITTED (emitSeqMux) ----
  // NOTE vs draft v2: v2 placed the activation as a BEHAVIOURAL CE-vs-0 mux in
  // this file. It is not needed - ser_organ applies ReLU internally
  // (act_k = and2(d_k, inv(d31))), so the accumulator feeds the organ directly
  // and THE ACTIVATION STAYS INSIDE THE KERNEL EMISSION rather than joining the
  // D2(b) hand-RTL exemption list. That is a boundary win, not a style choice.
  ser_organ ser0 (
    .clk(clk),
    .i0(act0),
    .i1(acc0[0]),
    .i2(acc0[1]),
    .i3(acc0[2]),
    .i4(acc0[3]),
    .i5(acc0[4]),
    .i6(acc0[5]),
    .i7(acc0[6]),
    .i8(acc0[7]),
    .i9(acc0[8]),
    .i10(acc0[9]),
    .i11(acc0[10]),
    .i12(acc0[11]),
    .i13(acc0[12]),
    .i14(acc0[13]),
    .i15(acc0[14]),
    .i16(acc0[15]),
    .i17(acc0[16]),
    .i18(acc0[17]),
    .i19(acc0[18]),
    .i20(acc0[19]),
    .i21(acc0[20]),
    .i22(acc0[21]),
    .i23(acc0[22]),
    .i24(acc0[23]),
    .i25(acc0[24]),
    .i26(acc0[25]),
    .i27(acc0[26]),
    .i28(acc0[27]),
    .i29(acc0[28]),
    .i30(acc0[29]),
    .i31(acc0[30]),
    .i32(acc0[31]),
    .o0(ser0_out)
  );
  ser_organ ser1 (
    .clk(clk),
    .i0(act1),
    .i1(acc1[0]),
    .i2(acc1[1]),
    .i3(acc1[2]),
    .i4(acc1[3]),
    .i5(acc1[4]),
    .i6(acc1[5]),
    .i7(acc1[6]),
    .i8(acc1[7]),
    .i9(acc1[8]),
    .i10(acc1[9]),
    .i11(acc1[10]),
    .i12(acc1[11]),
    .i13(acc1[12]),
    .i14(acc1[13]),
    .i15(acc1[14]),
    .i16(acc1[15]),
    .i17(acc1[16]),
    .i18(acc1[17]),
    .i19(acc1[18]),
    .i20(acc1[19]),
    .i21(acc1[20]),
    .i22(acc1[21]),
    .i23(acc1[22]),
    .i24(acc1[23]),
    .i25(acc1[24]),
    .i26(acc1[25]),
    .i27(acc1[26]),
    .i28(acc1[27]),
    .i29(acc1[28]),
    .i30(acc1[29]),
    .i31(acc1[30]),
    .i32(acc1[31]),
    .o0(ser1_out)
  );
  ser_organ ser2 (
    .clk(clk),
    .i0(act2),
    .i1(acc2[0]),
    .i2(acc2[1]),
    .i3(acc2[2]),
    .i4(acc2[3]),
    .i5(acc2[4]),
    .i6(acc2[5]),
    .i7(acc2[6]),
    .i8(acc2[7]),
    .i9(acc2[8]),
    .i10(acc2[9]),
    .i11(acc2[10]),
    .i12(acc2[11]),
    .i13(acc2[12]),
    .i14(acc2[13]),
    .i15(acc2[14]),
    .i16(acc2[15]),
    .i17(acc2[16]),
    .i18(acc2[17]),
    .i19(acc2[18]),
    .i20(acc2[19]),
    .i21(acc2[20]),
    .i22(acc2[21]),
    .i23(acc2[22]),
    .i24(acc2[23]),
    .i25(acc2[24]),
    .i26(acc2[25]),
    .i27(acc2[26]),
    .i28(acc2[27]),
    .i29(acc2[28]),
    .i30(acc2[29]),
    .i31(acc2[30]),
    .i32(acc2[31]),
    .o0(ser2_out)
  );

  // ---- emit-frame headers (adopted from draft v2, port-organ inlined) ----
  // Frame = [ACT,a2,ACT,a1,ACT,a0] in cycles 0..5, then payload 6..13.
  // dests: h0,h1 -> port 2 (010) · y -> port 5 (101). MSB-first (D4h).
  function hdr_bit; input [2:0] dest; input [3:0] c;
    hdr_bit = (c==4'd0||c==4'd2||c==4'd4) ? 1'b1
            : (c==4'd1) ? dest[2] : (c==4'd3) ? dest[1] : dest[0];
  endfunction
  wire em_f0 = (frm==5'd13);
  wire em_f1 = (frm==5'd17);
  wire em_f2 = (frm==5'd18);
  assign fab_in[0] = em_f0 ? (payload ? ser0_out : hdr_bit(3'd2, cyc)) : 1'b0;
  assign fab_in[1] = em_f1 ? (payload ? ser1_out : hdr_bit(3'd2, cyc)) : 1'b0;
  assign fab_in[2] = em_f2 ? (payload ? ser2_out : hdr_bit(3'd5, cyc)) : 1'b0;
  assign fab_in[3] = 1'b0;   // cell 3 idle

  wire _unused = &{ena, uio_in[7], uio_in[5:4], uio_in[1:0],
                   edge_in_vld, fab_out[6], fab_out[7], cnt_o,
                   acc3, 1'b0};

endmodule

`default_nettype wire
